version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /test_vue3
    container_name: test_vue3
    volumes:
      - .:/test_vue3
    command: sh -c "cd test_vue3 && npm run dev"
    ports:
        - "5173:5173"